exclude: >
    (?x)^(
        \.tox/.*
    )$
default_language_version:
  python: python3.7
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: .tox/dev/bin/isort
        language: python
        require_serial: true
        types: [python]
      - id: black
        name: black
        entry: .tox/dev/bin/black
        language: python
        require_serial: true
        types: [python]
      - id: flake8
        name: flake8
        entry: .tox/dev/bin/flake8
        language: python
        require_serial: true
        types: [python]
      - id: mypy
        name: mypy
        entry: .tox/dev/bin/mypy
        language: python
        require_serial: true
        types: [python]
