jobs:
- job:
  strategy:
    matrix:
      ubuntu-16.04:
        imageName: 'ubuntu-16.04'
      macos-10.14:
        imageName: 'macos-10.14'
        
  pool:
    vmImage: $(imageName)

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  
  # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
  # We need to take ownership if we want to update conda or install packages globally
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=macos
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      conda info
      conda list -n base

      conda env create --quiet --name tox --file tox.environment.yml
      conda list -n tox
    displayName: Install tox environment.

  - bash: |
      source activate tox
      tox -e py37-conda47
    displayName: Tox py37-conda47
    continueOnError: true

  - bash: |
      source activate tox
      tox -e py37-conda46
    displayName: Tox py37-conda46
    continueOnError: true
    
  - bash: |
      source activate tox
      tox -e py36-conda47
    displayName: Tox py36-conda47
    continueOnError: true

  - bash: |
      source activate tox
      tox -e py36-conda46
    displayName: Tox py36-conda46
    continueOnError: true
